/* autogenerated by Processing revision 1293 on 2024-09-11 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ColDet extends PApplet {

// Marco DalCanto | ColDet | Septemeber 9 2024
// int xspeed, yspeed, xpos, ypos, wdth, ht;
int xpos, ypos, xspeed, yspeed;
public void setup () {
  /* size commented out by preprocessor */;
  // size(displayWidth, displayHeight);
  background (0);
  xspeed = 3;
  yspeed = 10;
  // wdth = 20;
  // ht = 20;
  noStroke();
  xpos = width/2;
  ypos = height/2;
  frameRate(30);
}

public void draw () {
  // background(0);
  ball(20, 20, 1);
  ball(20, 20, 90);
}


public void ball (int wdth, int ht, int plus) {
  fill(255);
  ellipse(xpos+plus, ypos+plus, wdth, ht);
  xpos += xspeed;
  // to make the ball go vertical only, comment the previous line
  ypos += yspeed;
  if (xpos >= width-wdth/2 || xpos <= wdth/2) {
    xspeed = xspeed *-1;
  }
  if (ypos >= height-ht/2 || ypos<= ht/2) {
    yspeed = yspeed *-1;
  }
}


  public void settings() { size(1000, 1000); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ColDet" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
